import { FileText, Download, Eye, FileJson, Trash2, Clock, CheckCircle2, AlertCircle } from "lucide-react";
import { GeneratedReport } from "@/types/reports";
import ClientDate from "@/components/common/ClientDate";
import { downloadReportPdf, downloadReportJson, deleteReport } from "@/services/reports";

interface GeneratedReportsTableProps {
  reports: GeneratedReport[];
  onRefresh?: () => void;
}

export default function GeneratedReportsTable({ reports, onRefresh }: GeneratedReportsTableProps) {
  
  const handleDelete = async (id: string) => {
    try {
      await deleteReport(id);
      if (onRefresh) onRefresh();
    } catch (e) {
      console.error(e);
    }
  };

  return (
    <div className="glass-card rounded-xl overflow-hidden flex flex-col">
      <div className="p-4 border-b border-soc-border flex items-center justify-between">
        <h3 className="font-semibold text-white flex items-center gap-2">
          <FileText className="w-5 h-5 text-soc-accent" />
          Generated Reports
        </h3>
      </div>
      
      <div className="overflow-x-auto">
        <table className="w-full text-left border-collapse">
          <thead>
            <tr className="bg-soc-bg/50 text-gray-400 text-xs uppercase tracking-wider">
              <th className="px-6 py-3 font-medium">Report Name</th>
              <th className="px-6 py-3 font-medium">Type</th>
              <th className="px-6 py-3 font-medium">Generated By</th>
              <th className="px-6 py-3 font-medium">Time</th>
              <th className="px-6 py-3 font-medium">Status</th>
              <th className="px-6 py-3 font-medium text-right">Actions</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-soc-border">
            {reports.length === 0 ? (
              <tr>
                <td colSpan={6} className="px-6 py-8 text-center text-gray-400 text-sm">
                  No reports generated yet.
                </td>
              </tr>
            ) : reports.map((report) => (
              <tr key={report.id} className="hover:bg-soc-card-hover transition-colors group">
                <td className="px-6 py-4">
                  <div className="font-medium text-white text-sm">{report.name}</div>
                  <div className="text-xs text-gray-500 font-mono mt-0.5">{report.id} ({report.pages} pages)</div>
                </td>
                <td className="px-6 py-4 whitespace-nowrap text-xs text-gray-300">
                  <span className="px-2 py-1 bg-soc-bg border border-soc-border rounded">
                    {report.type}
                  </span>
                </td>
                <td className="px-6 py-4 text-sm text-gray-400">
                  {report.generated_by}
                </td>
                <td className="px-6 py-4 text-xs text-gray-400">
                  <ClientDate date={report.created_at} format="full" />
                </td>
                <td className="px-6 py-4">
                  <span className={`flex items-center text-xs font-medium ${
                    report.status === 'Ready' ? 'text-emerald-400' :
                    report.status === 'Generating' ? 'text-soc-warning animate-pulse' : 'text-red-400'
                  }`}>
                    {report.status === 'Ready' && <CheckCircle2 className="w-3.5 h-3.5 mr-1.5" />}
                    {report.status === 'Generating' && <Clock className="w-3.5 h-3.5 mr-1.5" />}
                    {report.status === 'Failed' && <AlertCircle className="w-3.5 h-3.5 mr-1.5" />}
                    {report.status}
                  </span>
                </td>
                <td className="px-6 py-4 text-right">
                  <div className="flex items-center justify-end gap-2 opacity-0 group-hover:opacity-100 transition-opacity">
                    <button onClick={() => downloadReportPdf(report.id)} className="p-1.5 text-gray-400 hover:text-white hover:bg-soc-bg rounded transition-colors tooltip-trigger" title="Download PDF">
                      <Download className="w-4 h-4" />
                    </button>
                    <button onClick={() => downloadReportJson(report.id)} className="p-1.5 text-gray-400 hover:text-white hover:bg-soc-bg rounded transition-colors tooltip-trigger" title="Download JSON">
                      <FileJson className="w-4 h-4" />
                    </button>
                    <button onClick={() => handleDelete(report.id)} className="p-1.5 text-gray-400 hover:text-red-400 hover:bg-soc-bg rounded transition-colors tooltip-trigger" title="Delete">
                      <Trash2 className="w-4 h-4" />
                    </button>
                  </div>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}
