import { FileText, Download, Printer } from "lucide-react";
import { GeneratedReport } from "@/types/reports";
import ClientDate from "@/components/common/ClientDate";
import { downloadReportPdf } from "@/services/reports";

interface ReportPreviewProps {
  report?: GeneratedReport;
}

export default function ReportPreview({ report }: ReportPreviewProps) {
  
  if (!report) {
    return (
      <div className="glass-card border border-soc-border rounded-xl flex flex-col h-[600px] xl:h-full items-center justify-center text-gray-500">
        <FileText className="w-10 h-10 mb-4 opacity-50" />
        <p>No report selected for preview.</p>
      </div>
    );
  }

  const content = report.content || {
    executive_summary: "N/A",
    incident_overview: "N/A",
    timeline: [],
    affected_assets: [],
    mitre_mapping: [],
    indicators_of_compromise: [],
    analyst_findings: "N/A",
    recommendations: "N/A",
    appendix: "N/A"
  };

  return (
    <div className="glass-card border border-soc-border rounded-xl flex flex-col h-[600px] xl:h-full relative overflow-hidden">
      {/* Toolbar */}
      <div className="px-4 py-3 border-b border-soc-border bg-soc-bg flex items-center justify-between sticky top-0 z-10">
        <div className="flex items-center gap-2 text-white font-medium text-sm">
          <FileText className="w-4 h-4 text-soc-accent" />
          Preview: {report.name}
        </div>
        <div className="flex items-center gap-2">
          <button className="p-1.5 text-gray-400 hover:text-white hover:bg-soc-card rounded transition-colors tooltip-trigger" title="Print (Coming Soon)"><Printer className="w-4 h-4" /></button>
          <button onClick={() => downloadReportPdf(report.id)} className="p-1.5 text-gray-400 hover:text-white hover:bg-soc-card rounded transition-colors tooltip-trigger" title="Download PDF"><Download className="w-4 h-4" /></button>
        </div>
      </div>

      {/* Document Content */}
      <div className="flex-1 overflow-y-auto bg-gray-900/50 p-8">
        <div className="max-w-[800px] mx-auto bg-white text-gray-900 p-10 rounded-sm shadow-2xl min-h-[1056px] print-page prose prose-sm max-w-none">
          
          <div className="border-b-2 border-blue-600 pb-4 mb-8 flex justify-between items-end">
            <div>
              <h1 className="text-3xl font-bold text-gray-900 m-0">{report.name}</h1>
              <p className="text-gray-500 font-medium mt-1">Chrona SOC Enterprise</p>
            </div>
            <div className="text-right">
              <p className="text-sm font-bold m-0 text-blue-600">CONFIDENTIAL</p>
              <p className="text-xs text-gray-500 mt-1">
                Generated: <ClientDate date={report.created_at} format="full" className="inline" />
              </p>
            </div>
          </div>

          <h2>1. Executive Summary</h2>
          <p>{content.executive_summary}</p>

          <h2>2. Incident Overview</h2>
          <p>{content.incident_overview}</p>

          {content.timeline && content.timeline.length > 0 && (
            <>
              <h2>3. Timeline</h2>
              <ul>
                {content.timeline.map((t, i) => (
                  <li key={i}><strong>{t.time}:</strong> {t.event}</li>
                ))}
              </ul>
            </>
          )}

          {content.affected_assets && content.affected_assets.length > 0 && (
            <>
              <h2>4. Affected Assets</h2>
              <ul>
                {content.affected_assets.map((a, i) => (
                  <li key={i}>{a}</li>
                ))}
              </ul>
            </>
          )}

          {content.mitre_mapping && content.mitre_mapping.length > 0 && (
            <>
              <h2>5. MITRE ATT&CK Mapping</h2>
              <ul>
                {content.mitre_mapping.map((m, i) => (
                  <li key={i}>{m}</li>
                ))}
              </ul>
            </>
          )}

          {content.indicators_of_compromise && content.indicators_of_compromise.length > 0 && (
            <>
              <h2>6. Indicators of Compromise</h2>
              <ul>
                {content.indicators_of_compromise.map((ioc, i) => (
                  <li key={i}><strong>{ioc.type}:</strong> {ioc.value}</li>
                ))}
              </ul>
            </>
          )}

          <h2>7. Analyst Findings</h2>
          <p>{content.analyst_findings}</p>

          <h2>8. Recommendations</h2>
          <p>{content.recommendations}</p>

          <h2>9. Appendix</h2>
          <p>{content.appendix}</p>

          <div className="mt-12 pt-8 border-t border-gray-300 text-center text-xs text-gray-400">
            Chrona SOC | Generated by {report.generated_by} | ID: {report.id}
          </div>
        </div>
      </div>
    </div>
  );
}
