import { FileText, Download, Printer } from "lucide-react";

export default function ReportPreview() {
  return (
    <div className="glass-card border border-soc-border rounded-xl flex flex-col h-[600px] xl:h-full relative overflow-hidden">
      {/* Toolbar */}
      <div className="px-4 py-3 border-b border-soc-border bg-soc-bg flex items-center justify-between sticky top-0 z-10">
        <div className="flex items-center gap-2 text-white font-medium text-sm">
          <FileText className="w-4 h-4 text-soc-accent" />
          Preview: Executive Summary (Oct 2023)
        </div>
        <div className="flex items-center gap-2">
          <button className="p-1.5 text-gray-400 hover:text-white hover:bg-soc-card rounded transition-colors"><Printer className="w-4 h-4" /></button>
          <button className="p-1.5 text-gray-400 hover:text-white hover:bg-soc-card rounded transition-colors"><Download className="w-4 h-4" /></button>
        </div>
      </div>

      {/* Document Content */}
      <div className="flex-1 overflow-y-auto bg-gray-900/50 p-8">
        <div className="max-w-[800px] mx-auto bg-white text-gray-900 p-10 rounded-sm shadow-2xl min-h-[1056px] print-page prose prose-sm max-w-none">
          
          <div className="border-b-2 border-blue-600 pb-4 mb-8 flex justify-between items-end">
            <div>
              <h1 className="text-3xl font-bold text-gray-900 m-0">Security Posture Report</h1>
              <p className="text-gray-500 font-medium mt-1">Chrona SOC Enterprise</p>
            </div>
            <div className="text-right">
              <p className="text-sm font-bold m-0 text-blue-600">CONFIDENTIAL</p>
              <p className="text-xs text-gray-500 mt-1">Generated: {new Date().toLocaleDateString()}</p>
            </div>
          </div>

          <h2>1. Executive Summary</h2>
          <p>
            During the period of <strong>Oct 1, 2023 - Oct 31, 2023</strong>, the SOC monitored and triaged a total of 14,892 alerts. 
            Overall security posture remains stable with a compliance score of <strong>89%</strong>. We observed a 14% decrease in critical 
            incidents compared to the previous month.
          </p>

          <div className="bg-gray-100 p-4 rounded-md my-6">
            <h4 className="text-sm font-bold uppercase tracking-wider text-gray-600 m-0 mb-2">AI Synthesized Assessment</h4>
            <p className="text-sm italic m-0">
              "The environment faced persistent scanning against edge firewalls, culminating in two isolated credential stuffing campaigns. 
              Both were thwarted by conditional access policies. No lateral movement or data exfiltration occurred."
            </p>
          </div>

          <h2>2. Incident Overview</h2>
          <table className="min-w-full text-left text-sm mt-4">
            <thead>
              <tr className="border-b border-gray-300">
                <th className="py-2">Severity</th>
                <th className="py-2">Count</th>
                <th className="py-2">Trend</th>
              </tr>
            </thead>
            <tbody>
              <tr className="border-b border-gray-200">
                <td className="py-2"><span className="text-red-600 font-bold">Critical</span></td>
                <td className="py-2">14</td>
                <td className="py-2 text-green-600">↓ 22%</td>
              </tr>
              <tr className="border-b border-gray-200">
                <td className="py-2"><span className="text-orange-500 font-bold">High</span></td>
                <td className="py-2">142</td>
                <td className="py-2 text-red-500">↑ 5%</td>
              </tr>
              <tr>
                <td className="py-2"><span className="text-blue-500 font-bold">Medium</span></td>
                <td className="py-2">834</td>
                <td className="py-2 text-green-600">↓ 12%</td>
              </tr>
            </tbody>
          </table>

          <h2>3. Top Attack Techniques (MITRE ATT&CK)</h2>
          <ul>
            <li><strong>T1059.001 - PowerShell:</strong> Predominantly seen in macro-enabled documents delivered via phishing.</li>
            <li><strong>T1078 - Valid Accounts:</strong> Detected via impossible travel alerts and anomalous login hours.</li>
            <li><strong>T1190 - Exploit Public-Facing Application:</strong> Automated scanning against legacy web infrastructure.</li>
          </ul>

          <div className="mt-12 pt-8 border-t border-gray-300 text-center text-xs text-gray-400">
            Chrona SOC | Generated by System | Page 1 of 4
          </div>
        </div>
      </div>
    </div>
  );
}
