import io
import uuid
import json
from datetime import datetime
from sqlalchemy.ext.asyncio import AsyncSession
from app.repositories.report_repo import report_repo, report_template_repo
from app.schemas.report_schema import ReportCreate, ReportContentSchema, ReportGenerateRequest
from app.services.base import BaseService
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.enums import TA_CENTER

class ReportService(BaseService):
    def __init__(self):
        super().__init__(report_repo)
        self.template_repo = report_template_repo

    async def generate_report_from_source(self, db: AsyncSession, request: ReportGenerateRequest):
        # 1. We mock the source data parsing for brevity but adhere to the architecture.
        # In a fully connected module, we'd inject AlertService / InvestigationService here.
        # For now, we generate a highly structured content payload based on the source type.
        
        content = ReportContentSchema(
            executive_summary=f"Automated {request.source_type} report generated for ID {request.source_id}. This report summarizes the critical findings and immediate mitigation strategies deployed.",
            incident_overview=f"An anomalous event was flagged via the {request.source_type} module. Initial triaging indicated suspicious behavior requiring deep-dive analysis.",
            timeline=[
                {"time": str(datetime.utcnow()), "event": f"{request.source_type} triggered"},
                {"time": str(datetime.utcnow()), "event": "Analyst assigned and triaged"}
            ],
            affected_assets=["CORP-LAPTOP-042", "10.0.5.15"],
            mitre_mapping=["T1059.001 - PowerShell", "T1078 - Valid Accounts"],
            indicators_of_compromise=[
                {"type": "IP", "value": "198.51.100.44"},
                {"type": "Hash", "value": "8d11c0620f3e69123b7b252033c467a2"}
            ],
            analyst_findings="The threat actor successfully bypassed primary defenses using stolen credentials, followed by encoded execution. Lateral movement was blocked by internal zero-trust rules.",
            recommendations="1. Reset all compromised credentials.\n2. Isolate CORP-LAPTOP-042 for forensics.\n3. Implement stricter MFA on VPN gateways.",
            appendix="System logs attached in external SIEM. Refer to Case #4492 for raw event correlation."
        )

        obj_in = ReportCreate(
            name=request.name,
            type=request.source_type,
            source_id=request.source_id,
            template_id=request.template_id,
            generated_by=request.generated_by,
            status="Ready",
            pages=3,
            content=content
        )

        db_obj = self.repository.model(**obj_in.dict(exclude_unset=True))
        db.add(db_obj)
        await db.commit()
        await db.refresh(db_obj)
        return db_obj

    async def get_pdf_bytes(self, db: AsyncSession, report_id: uuid.UUID) -> bytes:
        report = await self.repository.get(db, report_id)
        if not report:
            raise ValueError("Report not found")
        
        content = report.content or {}
        
        buffer = io.BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=letter, rightMargin=72, leftMargin=72, topMargin=72, bottomMargin=18)
        styles = getSampleStyleSheet()
        
        title_style = styles['Heading1']
        title_style.alignment = TA_CENTER
        
        h2 = styles['Heading2']
        body = styles['BodyText']
        
        Story = []
        
        Story.append(Paragraph(f"Chrona SOC - {report.name}", title_style))
        Story.append(Spacer(1, 12))
        
        Story.append(Paragraph(f"Type: {report.type}", body))
        Story.append(Paragraph(f"Generated By: {report.generated_by}", body))
        Story.append(Spacer(1, 12))
        
        sections = [
            ("Executive Summary", content.get("executive_summary", "")),
            ("Incident Overview", content.get("incident_overview", "")),
            ("Analyst Findings", content.get("analyst_findings", "")),
            ("Recommendations", content.get("recommendations", "")),
            ("Appendix", content.get("appendix", ""))
        ]
        
        for heading, text in sections:
            Story.append(Paragraph(heading, h2))
            Story.append(Paragraph(str(text), body))
            Story.append(Spacer(1, 12))
            
        doc.build(Story)
        pdf_value = buffer.getvalue()
        buffer.close()
        return pdf_value

report_service = ReportService()
