"""add_org_id_to_threat_intel

Revision ID: 64e30c760c85
Revises: 1efb1acecf9d
Create Date: 2026-08-11 18:02:08.484512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64e30c760c85'
down_revision: Union[str, None] = '1efb1acecf9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('iocs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('org_id', sa.UUID(), nullable=True))
        batch_op.create_index(batch_op.f('ix_iocs_org_id'), ['org_id'], unique=False)
        batch_op.create_foreign_key('fk_iocs_org_id_organizations', 'organizations', ['org_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('malware', schema=None) as batch_op:
        batch_op.add_column(sa.Column('org_id', sa.UUID(), nullable=True))
        batch_op.create_index(batch_op.f('ix_malware_org_id'), ['org_id'], unique=False)
        batch_op.create_foreign_key('fk_malware_org_id_organizations', 'organizations', ['org_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('threat_actors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('org_id', sa.UUID(), nullable=True))
        batch_op.create_index(batch_op.f('ix_threat_actors_org_id'), ['org_id'], unique=False)
        batch_op.create_foreign_key('fk_threat_actors_org_id_organizations', 'organizations', ['org_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('threat_feeds', schema=None) as batch_op:
        batch_op.add_column(sa.Column('org_id', sa.UUID(), nullable=True))
        batch_op.create_index(batch_op.f('ix_threat_feeds_org_id'), ['org_id'], unique=False)
        batch_op.create_foreign_key('fk_threat_feeds_org_id_organizations', 'organizations', ['org_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('threat_feeds', schema=None) as batch_op:
        batch_op.drop_constraint('fk_threat_feeds_org_id_organizations', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_threat_feeds_org_id'))
        batch_op.drop_column('org_id')

    with op.batch_alter_table('threat_actors', schema=None) as batch_op:
        batch_op.drop_constraint('fk_threat_actors_org_id_organizations', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_threat_actors_org_id'))
        batch_op.drop_column('org_id')

    with op.batch_alter_table('malware', schema=None) as batch_op:
        batch_op.drop_constraint('fk_malware_org_id_organizations', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_malware_org_id'))
        batch_op.drop_column('org_id')

    with op.batch_alter_table('iocs', schema=None) as batch_op:
        batch_op.drop_constraint('fk_iocs_org_id_organizations', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_iocs_org_id'))
        batch_op.drop_column('org_id')
    # ### end Alembic commands ###
