"""add_status_category_iocs

Revision ID: 7c26d6f49135
Revises: 64e30c760c85
Create Date: 2026-08-11 20:31:58.746011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c26d6f49135'
down_revision: Union[str, None] = '64e30c760c85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('iocs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('category', sa.String(length=100), nullable=True))

    # Set default values for existing rows
    op.execute("UPDATE iocs SET status = 'Active' WHERE status IS NULL")
    
    with op.batch_alter_table('iocs', schema=None) as batch_op:
        # We leave category nullable, but if we wanted status to be NOT NULL we would alter here.
        pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('iocs', schema=None) as batch_op:
        batch_op.drop_column('category')
        batch_op.drop_column('status')
    # ### end Alembic commands ###
