"""Update Alert model for Detection Engine

Revision ID: 8177a159920d
Revises: 9f4aa73ddcce
Create Date: 2026-07-25 23:22:08.289226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8177a159920d'
down_revision: Union[str, None] = '9f4aa73ddcce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('alerts', sa.Column('confidence', sa.Integer(), nullable=True))
    op.add_column('alerts', sa.Column('source_rule', sa.String(length=100), nullable=True))
    op.add_column('alerts', sa.Column('mitre_mapping', sa.JSON(), nullable=True))
    op.add_column('alerts', sa.Column('related_events', sa.JSON(), nullable=True))
    # ### end Alembic commands ###
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alerts', 'related_events')
    op.drop_column('alerts', 'mitre_mapping')
    op.drop_column('alerts', 'source_rule')
    op.drop_column('alerts', 'confidence')
    op.drop_column('alerts', 'description')
    # ### end Alembic commands ###
