"""Add attack graph entities

Revision ID: b8363bd78100
Revises: fddc8a28bdc3
Create Date: 2026-08-09 11:59:12.221759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8363bd78100'
down_revision: Union[str, None] = 'fddc8a28bdc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.Column('ip_address', sa.String(length=100), nullable=True),
    sa.Column('hostname', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('criticality', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assets_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_name'), ['name'], unique=False)

    op.create_table('malware',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('family', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('malware', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_malware_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_malware_name'), ['name'], unique=True)

    op.create_table('mitre_techniques',
    sa.Column('technique_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('tactic', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mitre_techniques', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mitre_techniques_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mitre_techniques_technique_id'), ['technique_id'], unique=True)

    op.create_table('report_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('estimated_pages', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('threat_actors',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('aliases', sa.JSON(), nullable=True),
    sa.Column('reputation', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('threat_actors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_threat_actors_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_threat_actors_name'), ['name'], unique=True)

    op.create_table('malware_iocs',
    sa.Column('malware_id', sa.UUID(), nullable=False),
    sa.Column('ioc_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['ioc_id'], ['iocs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['malware_id'], ['malware.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('malware_id', 'ioc_id')
    )
    op.create_table('threat_actor_iocs',
    sa.Column('threat_actor_id', sa.UUID(), nullable=False),
    sa.Column('ioc_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['ioc_id'], ['iocs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['threat_actor_id'], ['threat_actors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('threat_actor_id', 'ioc_id')
    )
    op.create_table('threat_actor_malware',
    sa.Column('threat_actor_id', sa.UUID(), nullable=False),
    sa.Column('malware_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['malware_id'], ['malware.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['threat_actor_id'], ['threat_actors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('threat_actor_id', 'malware_id')
    )
    op.create_table('alert_assets',
    sa.Column('alert_id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('alert_id', 'asset_id')
    )
    op.create_table('alert_mitre_techniques',
    sa.Column('alert_id', sa.UUID(), nullable=False),
    sa.Column('mitre_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mitre_id'], ['mitre_techniques.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('alert_id', 'mitre_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alert_mitre_techniques')
    op.drop_table('alert_assets')
    op.drop_table('threat_actor_malware')
    op.drop_table('threat_actor_iocs')
    op.drop_table('malware_iocs')
    with op.batch_alter_table('threat_actors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_threat_actors_name'))
        batch_op.drop_index(batch_op.f('ix_threat_actors_id'))

    op.drop_table('threat_actors')
    op.drop_table('mitre_techniques')
    with op.batch_alter_table('malware', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_malware_name'))
        batch_op.drop_index(batch_op.f('ix_malware_id'))

    op.drop_table('malware')
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assets_name'))
        batch_op.drop_index(batch_op.f('ix_assets_id'))

    op.drop_table('assets')
    # ### end Alembic commands ###
