"""add integration credentials

Revision ID: fddc8a28bdc3
Revises: 2449379bedbe
Create Date: 2026-08-08 19:40:29.411435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fddc8a28bdc3'
down_revision: Union[str, None] = '2449379bedbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('integration_credentials',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('encrypted_secret', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('integration_credentials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_integration_credentials_id'), ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('integration_credentials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_integration_credentials_id'))

    op.drop_table('integration_credentials')
    # ### end Alembic commands ###
